<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LibImportDn8\LibImportDn8.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="tmpl\idektp_bk\IDEKTP_670_Emblem_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mydl_bk\MYDL_BK_670_Flower_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mydl_fr\MYDL_670_COA_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mydl_fr\MYDL_670_Flag_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mydl_fr\MYDL_670_Flower_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad\MyKad_670_Flag.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad\MyKad_670_Flag_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad\MyKad_670_Flag_MoonStar.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad\MyKad_670_Flag_MoonStar_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad\MyKad_670_Flower_Front_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad\MyKad_670_IC_Chip.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad\MyKad_670_IC_Chip_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad\MyKad_670_IC_Chip_old.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad\MyKad_670_IC_Chip_old_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad\MyKad_670_MSC_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad\MyKad_670_MyKad.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad\MyKad_670_MyKad_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad_bk\MyKad_BK_670_chip_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad_bk\MyKad_BK_670_CHIP_new_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad_bk\MyKad_BK_670_COA.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad_bk\MyKad_BK_670_COA_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad_bk\MyKad_BK_670_COA_new_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad_bk\MyKad_BK_670_COA_old_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad_bk\MyKad_BK_670_CROWN_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad_bk\MyKad_BK_670_CROWN_new_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad_bk\MyKad_BK_670_KETUA_PENGARAH_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad_bk\MyKad_BK_670_KETUA_PENGARAH_new_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad_bk\MyKad_BK_670_MALAYSIA_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad_bk\MyKad_BK_670_MALAYSIA_new_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad_bk\MyKad_BK_670_TnG.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad_bk\MyKad_BK_670_TnG_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad_bk\MyKad_BK_670_TnG_no_frame.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad_bk\MyKad_BK_670_TnG_no_frame_2_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad_bk\MyKad_BK_670_TnG_no_frame_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad_bk\MyKad_BK_670_TWINTOWER_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad_bk\MyKad_BK_670_TWINTOWER_new_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad_fr\MyKad_FR_670_Flag_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad_fr\MyKad_FR_670_Flower_Front_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad_fr\MyKad_FR_670_IC_Chip_Gray_L.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad_fr\MyKad_FR_670_IC_Chip_Gray_S.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad_fr\MyKad_FR_670_MALAYSIA_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad_fr\MyKad_FR_670_MSC_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad_fr\MyKad_FR_670_MyKad_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad_old_bk\MyKad_old_BK_670_chip_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad_old_bk\MyKad_old_BK_670_COA_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad_old_bk\MyKad_old_BK_670_Crown_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad_old_bk\MyKad_old_BK_670_TwinTower_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad_old_fr\MyKad_old_FR_670_IC_Chip_Gray_L.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad_old_fr\MyKad_old_FR_670_IC_Chip_Gray_S.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\mykad_old_fr\MyKad_old_FR_670_MALAYSIA_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\phdl_fr\PHDL_Flag.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\phdl_fr\PHDL_Logo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\phni_fr\PHNI_670_COA.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\phni_fr\PHNI_670_Logo_Fingerprint.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\phni_fr\PHNI_670_Logo_Right_Bottom.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\phni_fr\PHNI_670_PHL.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\phni_fr\PHNI_fr.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\phni_fr\PSA_watermark.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\phumid_fr\PHUMID_670_LogoL_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmpl\phumid_fr\PHUMID_670_LogoR_Gray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
